# Generated by Django 4.2.13 on 2024-06-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comment_delete_dummymodel'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_value_valid', violation_error_message='Invalid rating: it must fall between 1 and 5'),
        ),
    ]
