# Generated by Django 4.2.13 on 2024-06-21 19:34

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rating_rating_value_valid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'get_latest_by': 'date_opened', 'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(check=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='valid_latitude', violation_error_message='Invalid latitude: it must fall between -90 and 90'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(check=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='valid_longitude', violation_error_message='Invalid longitude: it must fall between -180 and 180'),
        ),
    ]
