# Generated by Django 4.2.13 on 2024-06-21 19:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_restaurant_options_restaurant_valid_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[core.models.validate_restaurant_name_tarts_with_a]),
        ),
    ]
