# Generated by Django 4.2.13 on 2024-06-21 20:01

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_restaurant_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'restaurant'), name='user_restaurant_uniq'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='name_uniq_constraint'),
        ),
    ]
