# Generated by Django 4.2.13 on 2024-06-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rating_user_restaurant_uniq_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='user_restaurant_uniq',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='nickname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
