# Generated by Django 4.2.13 on 2024-06-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_rating_user_restaurant_uniq_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'restaurant'), name='user_restaurant_uniq'),
        ),
    ]
